-- =============================================================================
-- Blue Belt Media — Tournament Watcher: canonical baseline schema
-- =============================================================================
-- Reproduces, from a clean Supabase project, every table the app touches with
-- its foreign keys, constraints, indexes, RLS policies and triggers. Every
-- statement is idempotent so this file can also be applied on top of an
-- existing project (it was written against the live schema on 2026-10-02).
--
-- Isolation model: every row carries owner_id = auth.uid() and every policy
-- is "(select auth.uid()) = owner_id". Nothing here widens that.
-- =============================================================================

create extension if not exists pgcrypto;

-- updated_at maintenance -------------------------------------------------------
create or replace function public.photo_set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- photo_events -----------------------------------------------------------------
create table if not exists public.photo_events (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text not null,
  venue text,
  country text,
  event_date date,
  platform text not null,
  source_url text,
  timezone text not null default 'Asia/Qatar',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint photo_events_platform_check check (platform = any (array['AJP'::text, 'SMOOTHCOMP'::text, 'OTHER'::text]))
);
alter table public.photo_events add column if not exists country text;
create index if not exists photo_events_owner_idx on public.photo_events (owner_id);

-- photo_athletes ---------------------------------------------------------------
create table if not exists public.photo_athletes (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  event_id uuid references public.photo_events (id) on delete cascade,
  name text not null,
  phone text,
  email text,
  division text,
  academy text,
  platform text not null default 'AJP',
  source_url text,
  notes text,
  belt text,
  weight text,
  gender text,
  age_category text,
  package_name text,
  internal_notes text,
  last_checked_at timestamptz,
  last_watch_status text,
  last_watch_message text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint photo_athletes_platform_check check (platform = any (array['AJP'::text, 'SMOOTHCOMP'::text, 'OTHER'::text]))
);
create index if not exists photo_athletes_owner_idx on public.photo_athletes (owner_id);
create index if not exists photo_athletes_event_idx on public.photo_athletes (event_id);

-- photo_matches ----------------------------------------------------------------
create table if not exists public.photo_matches (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  athlete_id uuid not null references public.photo_athletes (id) on delete cascade,
  external_match_id text,
  opponent text,
  mat text,
  scheduled_at timestamptz,
  estimated_at timestamptz,
  status text not null default 'scheduled',
  match_order integer,
  source_url text,
  last_checked_at timestamptz,
  last_changed_at timestamptz,
  raw_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists photo_matches_owner_idx on public.photo_matches (owner_id);
create index if not exists photo_matches_athlete_idx on public.photo_matches (athlete_id);
create index if not exists photo_matches_eta_idx on public.photo_matches (estimated_at);
create unique index if not exists photo_matches_athlete_external_uidx
  on public.photo_matches (athlete_id, external_match_id) where external_match_id is not null;

-- photo_match_history ----------------------------------------------------------
create table if not exists public.photo_match_history (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  match_id uuid not null references public.photo_matches (id) on delete cascade,
  change_type text not null,
  old_value jsonb,
  new_value jsonb,
  detected_at timestamptz not null default now()
);
create index if not exists photo_match_history_owner_detected_idx on public.photo_match_history (owner_id, detected_at desc);

-- Bookings / payments (prepared; not on the watcher's critical path) ----------
create table if not exists public.photo_bookings (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  event_id uuid references public.photo_events (id) on delete set null,
  athlete_name text not null,
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  academy text,
  division text,
  package_name text not null,
  amount_qr numeric not null,
  currency text not null default 'QAR',
  status text not null default 'pending',
  provider text not null default 'MYFATOORAH',
  provider_invoice_id text,
  payment_url text,
  paid_at timestamptz,
  watcher_athlete_id uuid references public.photo_athletes (id) on delete set null,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint photo_bookings_amount_qr_check check (amount_qr >= 0::numeric)
);
create index if not exists photo_bookings_event_idx on public.photo_bookings (event_id);
create index if not exists photo_bookings_status_idx on public.photo_bookings (status);

create table if not exists public.photo_orders (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  pictime_order_id text unique,
  customer_name text not null,
  customer_email text,
  customer_phone text,
  gallery_name text,
  amount_qr numeric not null,
  currency text not null default 'QAR',
  status text not null default 'pending',
  provider text default 'MYFATOORAH',
  provider_invoice_id text,
  payment_url text,
  paid_at timestamptz,
  approved_in_pictime_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint photo_orders_amount_qr_check check (amount_qr >= 0::numeric)
);
create index if not exists photo_orders_status_idx on public.photo_orders (status);

create table if not exists public.photo_payment_events (
  id bigint generated by default as identity primary key,
  owner_id uuid,
  order_id uuid references public.photo_orders (id) on delete set null,
  provider text not null,
  provider_event_id text,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now()
);

-- Triggers ---------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array['photo_events', 'photo_athletes', 'photo_matches', 'photo_bookings', 'photo_orders'] loop
    execute format('drop trigger if exists %I on public.%I', t || '_set_updated_at', t);
    execute format('create trigger %I before update on public.%I for each row execute function public.photo_set_updated_at()', t || '_set_updated_at', t);
  end loop;
end $$;

-- Row Level Security -----------------------------------------------------------
-- Owner-only policies for every table. The helper creates the four standard
-- policies when missing, so re-running never duplicates them.
create or replace function public.photo_ensure_owner_policies(p_table text)
returns void language plpgsql as $$
begin
  execute format('alter table public.%I enable row level security', p_table);
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = p_table and policyname = p_table || '_owner_select') then
    execute format('create policy %I on public.%I for select using ((select auth.uid()) = owner_id)', p_table || '_owner_select', p_table);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = p_table and policyname = p_table || '_owner_insert') then
    execute format('create policy %I on public.%I for insert with check ((select auth.uid()) = owner_id)', p_table || '_owner_insert', p_table);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = p_table and policyname = p_table || '_owner_update') then
    execute format('create policy %I on public.%I for update using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id)', p_table || '_owner_update', p_table);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = p_table and policyname = p_table || '_owner_delete') then
    execute format('create policy %I on public.%I for delete using ((select auth.uid()) = owner_id)', p_table || '_owner_delete', p_table);
  end if;
end $$;

select public.photo_ensure_owner_policies('photo_events');
select public.photo_ensure_owner_policies('photo_athletes');
select public.photo_ensure_owner_policies('photo_matches');
select public.photo_ensure_owner_policies('photo_match_history');
select public.photo_ensure_owner_policies('photo_bookings');
select public.photo_ensure_owner_policies('photo_orders');

-- Payment events are written by the server (service role) and only read by owners.
alter table public.photo_payment_events enable row level security;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'photo_payment_events' and policyname = 'photo_payment_events_owner_select') then
    create policy photo_payment_events_owner_select on public.photo_payment_events for select using ((select auth.uid()) = owner_id);
  end if;
end $$;
